const USER_CONSTANT = {
  MIN_NAME_LENGTH: 1,
  MAX_NAME_LENGTH: 10,
  MIN_NICKNAME_LENGTH: 1,
  MAX_NICKNAME_LENGTH: 10,
  MIN_PASSWORD_LENGTH: 6,
  MAX_PASSWORD_LENGTH: 14,
};

export { USER_CONSTANT };
